### ISSUE TITLE
error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by burningthumb** [googlesamples/android-DirectorySelection#6]
I imported this into Android studio and when I try to build it fails.  Not a great sample code experience.

**Comment by burningthumb** [comment]
So the first error can be fixed as:
```

dependencies {
    implementation "com.android.support:support-v4:27.1.1"
    implementation "com.android.support:support-v13:27.1.1"
    implementation "com.android.support:cardview-v7:27.1.1"
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation 'com.android.support:recyclerview-v7:27.1.1'
}
```

**Comment by burningthumb** [comment]
Which leads to the second error which can be fixed as:

```
        Uri directoryUri = null;
        try
        {
            directoryUri = DocumentsContract
                    .createDocument(contentResolver, docUri, Document.MIME_TYPE_DIR, directoryName);
        } catch (FileNotFoundException e)
        {
            e.printStackTrace();
        }
```

**Comment by burningthumb** [comment]
Which leads to the next error (at least it runs now - too bad it does not work):

```
07-07 15:36:24.923 30919-30919/com.example.android.directoryselection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.directoryselection, PID: 30919
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
        at android.app.Activity.startActivityForResult(Activity.java:4224)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:830)
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1021)
        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1010)
        at com.example.android.directoryselection.DirectorySelectionFragment$1.onClick(DirectorySelectionFragment.java:96)
        at android.view.View.performClick(View.java:5595)
        at android.view.View.onKeyUp(View.java:10566)
        at android.widget.TextView.onKeyUp(TextView.java:6377)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2699)
        at android.view.View.dispatchKeyEvent(View.java:9865)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:403)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1800)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3021)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:317)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4338)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4309)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3860)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3913)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3879)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4006)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3887)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4063)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3860)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3913)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3879)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3887)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3860)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3913)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3879)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4039)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4200)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2365)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1961)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1952)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2342)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
07-07 15:36:24.924 30919-30919/com.example.android.directoryselection E/AndroidRuntime:     at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
07-07 15:36:24.935 1773-2972/? W/ActivityManager:   Force finishing activity com.example.android.directoryselection/.DirectorySelectionActivity
```

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
